[package]
name = "jjpwrgem"
description = "jjpwrgem json parser with really good error messages"
version = "0.1.0"
edition = "2024"

[dependencies]
annotate-snippets = "0.12.8"
anstream = "0.6.21"
displaydoc = "0.2.5"
thiserror = "2.0.17"

[dev-dependencies]
insta = "1.44.1"
rstest = "0.26.1"
rstest_reuse = "0.7.0"

[lints.clippy]

[[bin]]
name = "jjp"
path = "src/main.rs"
