[package]
name = "jjpwrgem-parse"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
displaydoc = { workspace = true }
itertools = "0.14.0"
thiserror = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
rstest_reuse = { workspace = true }
