[package]
name = "jjpwrgem-parse"
version = "0.2.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
displaydoc = { workspace = true }
itertools = "0.14.0"
serde = { version = "1", optional = true }
serde_json = { version = "1", features = [
  "arbitrary_precision",
  "preserve_order",
], optional = true }
thiserror = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
rstest_reuse = { workspace = true }

[features]
serde = ["dep:serde", "dep:serde_json"]
