[package]
name = "jjpwrgem-parse"
version = "0.1.0"
edition = "2024"

[dependencies]
annotate-snippets = { workspace = true }
displaydoc = "0.2.5"
itertools = "0.14.0"
thiserror = "2.0.17"

[dev-dependencies]
rstest = "0.26.1"
rstest_reuse = "0.7.0"
