[tools]
bun = "latest"
python = "3.13"
uv = "latest"
"npm:json-minify" = "latest"
"npm:prettier" = "latest"
"pipx:jello" = "latest"
jaq = "latest"
gojq = "latest"
jq = "latest"
"github:caarlos0/jsonfmt" = "latest"
"github:swaggest/json-cli" = "latest"
"github:tdewolff/minify" = "latest"
"github:tidwall/jj" = "latest"
