name: Host npm

on:
  workflow_call:
    inputs:
      plan:
        description: Dist release plan JSON payload
        required: true
        type: string

jobs:
  host:
    name: host npm
    runs-on: ubuntu-latest
    env:
      PLAN: ${{ inputs.plan }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install just
        uses: taiki-e/install-action@just
      - name: Generate npm package manifest
        run: just package-json

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"

      - name: Tar npm package
        working-directory: npm-template
        run: tar -czvf ../npm-package.tar.gz .

      - name: Upload npm package artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ github.ref_name }}-npm-package.tar.gz
          path: npm-package.tar.gz
