name: verify

on:
  pull_request:
    branches:
      - main
      - "**"
  push:
    branches:
      - main

env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: always
  TOOLCHAIN: stable
  CI: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: update rust
        run: rustup update ${{ env.TOOLCHAIN }} && rustup default ${{ env.TOOLCHAIN }}
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Configure Dependency Caching
        uses: Swatinem/rust-cache@v2

      - name: check formatting
        run: just format-check

  lint:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@v6
      - name: update rust
        run: rustup update ${{ env.TOOLCHAIN }} && rustup default ${{ env.TOOLCHAIN }}
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Install cargo-shear
        uses: taiki-e/install-action@cargo-shear
      - name: Configure Dependency Caching
        uses: Swatinem/rust-cache@v2

      - name: check unused dependencies
        run: cargo shear
      - name: lint
        run: just lint
      - run: just readmes-check
      - run: just package-json-check

  test-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: update rust
        run: rustup update ${{ env.TOOLCHAIN }} && rustup default ${{ env.TOOLCHAIN }}
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Configure Dependency Caching
        uses: Swatinem/rust-cache@v2
      - name: build
        run: cargo build --release --verbose
      - name: test
        run: cargo test --workspace --verbose

  test-vscode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: update rust
        run: rustup update ${{ env.TOOLCHAIN }} && rustup default ${{ env.TOOLCHAIN }}
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Configure Dependency Caching
        uses: Swatinem/rust-cache@v2
      - name: build
        run: just vscode-bin
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true
      - run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & echo "Started xvfb"
        shell: bash
      - run: pnpm --filter jjpwrgem-vscode test
        env:
          DISPLAY: ":99.0"
